familybankingsystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Landing_Page.as_view(), name="landing_page"),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('tasks/', views.Task_List.as_view(), name="task_list"),
    path('tasks/new/', views.Task_Create.as_view(), name="task_create"),
    path('tasks/<int:pk>/', views.Task_Detail.as_view(), name="task_detail"),
    path('tasks/<int:pk>/update', views.Task_Update.as_view(), name="task_update"),
    path('tasks/<int:pk>/delete', views.Task_Delete.as_view(), name="task_delete"),
    path('user/<username>/', views.profile, name='profile'),
    path('transactions/', views.transactions_index, name='transactions_index'),
    path('transactions/<int:transaction_id>', views.transactions_show, name='transactions_show'),
    path('transactions/create/', views.Transaction_Create.as_view(), name='transactions_create'),
    path('transactions/<int:pk>/update/', views.Transaction_Update.as_view(), name='transactions_update'),
    path('transactions/<int:pk>/delete/', views.Transaction_Delete.as_view(), name='transactions_delete'),
    path('dashboard/', views.Dashboard.as_view(), name="dashboard"),
    # path('families/', views.Family_List.as_view(), name="family_list"),
    # path('families/new/', views.Family_Create.as_view(), name="family_create"),
    # path('families/<int:pk>/', views.Family_Detail.as_view(), name="family_detail"),
    # path('families/<int:pk>/update', views.Family_Update.as_view(), name="family_update"),
    # path('families/<int:pk>/delete', views.Family_Delete.as_view(), name="family_delete"),
    path('families/', views.families_index, name='families_index'),
    path('families/<int:family_id>', views.families_show, name='families_show'),
    path('families/create/', views.Family_Create.as_view(), name='families_create'),
    path('families/<int:pk>/update/', views.Family_Update.as_view(), name='families_update'),
    path('families/<int:pk>/delete/', views.Family_Delete.as_view(), name='families_delete'),

]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.

class Family(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name



class Transaction(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(default=timezone.now)
    sending_user = models.ForeignKey(User, related_name='sending_user', on_delete=models.CASCADE)
    receiving_user = models.ForeignKey(User, related_name='receiving_user', on_delete=models.CASCADE)

    def __str__(self):
        # return self.transaction_number
         return ": $" + str(self.amount)

# class Transaction(models.Model):
#     amount = models.DecimalField(max_digits=10, decimal_places=2)
#     date = models.DateTimeField(default=timezone.now)
#     sending_user = models.ForeignKey(User, on_delete=models.CASCADE)
#     receiving_user = models.ForeignKey(User, on_delete=models.CASCADE)

#     def __str__(self):
#         # return self.transaction_number
#          return ": $" + str(self.amount)

STATUS_CHOICES = {
    ("Not yet started", "not yet started"), 
    ("Completed", "complete"), 
    ("Incomplete", "incomplete")
}

# USER_CHOICES ={
#     ("child", "child"),
#     ("parent", "parent")
# }


class Task(models.Model):
    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    duedate = models.DateTimeField()
    description = models.CharField(max_length=200)
    task_status = models.CharField(max_length=20, choices = STATUS_CHOICES)
    task_approval = models.BooleanField()
    # user = models.ManyToManyField(User) # M:M example
    family = models.ManyToManyField(Family) # M:M example
    # transactions = models.ManyToManyField(Transaction) # M:M example
    # family = models.ForeignKey(Family, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return self.name
        # return str(self.item) + ": $" + str(self.price)

    class Meta: 
        ordering = ['name']


 
# class Transaction(models.Model):
#     amount = models.DecimalField(max_digits=10, decimal_places=2)
#     date = models.DateTimeField(default=timezone.now)
#     sending_user = models.ForeignKey(User, related_name='sending_user', on_delete=models.CASCADE)
#     receiving_user = models.ForeignKey(User, related_name='receiving_user', on_delete=models.CASCADE)

#     def __str__(self):
#         # return self.transaction_number
#          return ": $" + str(self.amount)

main_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms




class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()



    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2' )

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views import View 
from django.views.generic import DetailView, CreateView, DeleteView, UpdateView
from django.http import HttpResponse, HttpResponseRedirect 
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.urls import reverse
from .models import Family, Task, Transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from .forms import SignUpForm




# Create your views here.

def login_view(request):
    # if POST, then authenticate the user (submitting the username and password)
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            user = authenticate(username = u, password = p)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/dashboard/')
                else:
                    return render(request, 'login.html', {'form': form})
            else:
                return render(request, 'login.html', {'form': form})
        else: 
            return render(request, 'signup.html', {'form': form})
    else: # it was a get request so send the emtpy login form
        # form = LoginForm()
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})



def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')



def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})




class Landing_Page(TemplateView): 
    template_name = 'landing_page.html'

class Dashboard(TemplateView): 
    template_name = 'dashboard.html'



class Task_List(TemplateView):
    template_name = 'tasklist.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name")
        if name != None:
            # .filter is the sql WHERE statement and name__icontains is doing a search for any name that contains the query param
            context['tasks'] = Task.objects.filter(name_icontains=name)
            context['header'] = f"Searching for {name}"
        else:
            context['tasks'] = Task.objects.all()
            context['header'] = "Daily Tasks" # this is where we add the key into our context object for the view to use
        return context 


class Task_Create(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['name', 'amount', 'duedate', 'description', 'task_status', 'task_approval']
    template_name = "task_create.html"
    success_url = '/'
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/tasks')

   

class Task_Detail(DetailView): 
    model = Task
    template_name="task_detail.html"

class Task_Update(UpdateView):
    model = Task
    fields = ['name', 'amount', 'duedate', 'description', 'task_status', 'task_approval', 'families']
    template_name = "task_update.html"
    # success_url = "/tasks/"
    def get_success_url(self):
        return reverse('task_detail', kwargs={'pk': self.object.pk})

class Task_Delete(DeleteView):
    model = Task
    template_name = "task_delete_confirmation.html"
    success_url = "/tasks/"


def profile(request, username):
    user = User.objects.get(username=username)
    tasks = Task.objects.filter(user=user)
    return render(request, 'profile.html', {'username': username, 'tasks': tasks})



# Transactions view function

def transactions_index(request):
    transactions = Transaction.objects.all()
    return render(request, 'transaction_index.html', {'transactions': transactions})

def transactions_show(request, transaction_id):
    transaction = Transaction.objects.get(id=transaction_id)
    return render(request, 'transaction_show.html', {'transaction': transaction})



class Transaction_Create(CreateView):
    model = Transaction
    fields = '__all__'
    template_name = "transaction_create.html"
    success_url = '/transactions'



class Transaction_Update(UpdateView):
    model = Transaction
    fields = ['amount', 'date']
    template_name = "transaction_update.html"
    success_url = '/transactions'



class Transaction_Delete(DeleteView):
    model = Transaction
    template_name = "transaction_confirm_delete.html"
    success_url = '/transactions'



# Families view function

def families_index(request):
    families = Family.objects.all()
    return render(request, 'family_index.html', {'families': families})

def families_show(request, family_id):
    family = Family.objects.get(id=family_id)
    return render(request, 'family_show.html', {'family': family})



class Family_Create(CreateView):
    model = Task
    fields = ['name', 'description']
    template_name = "family_create.html"
    success_url = "/families/"



class Family_Update(UpdateView):
    model = Task
    fields = ['name', 'description']
    template_name = "family_update.html"
    success_url = "/families"


class Family_Delete(DeleteView):
    model = Task
    template_name = "family_delete_confirmation.html"
    success_url = "/families/"







# class Family_List(TemplateView):
#     template_name = 'familylist.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         fam_name = self.request.GET.get("fam_name")
#         if fam_name != None:
#             # .filter is the sql WHERE statement and name__icontains is doing a search for any name that contains the query param
#             context['families'] = Family.objects.filter(name_icontains=fam_name)
#             context['header'] = f"Searching for {fam_name}"
#         else:
#             context['families'] = Family.objects.all()
#             context['header'] = "My Family Members" # this is where we add the key into our context object for the view to use
#         return context 


# class Family_Create(LoginRequiredMixin, CreateView):
#     model = Family
#     fields = ['fam_name', 'description']
#     template_name = "family_create.html"
#     success_url = '/families'
#     def form_valid(self, form):
#         self.object = form.save(commit=False)
#         self.object.user = self.request.user
#         self.object.save()
#         return HttpResponseRedirect('/families/')

   

# class Family_Detail(DetailView): 
#     model = Family
#     template_name="family_detail.html"

# class Family_Update(UpdateView):
#     model = Family
#     fields = ['fam_name', 'description']
#     template_name = "family_update.html"
#     def get_success_url(self):
#         return reverse('family_detail', kwargs={'pk': self.object.pk})

# class Family_Delete(DeleteView):
#     model = Task
#     template_name = "family_delete_confirmation.html"
#     success_url = "/families/"

main_app/templates/family_create.html
{% extends 'base.html' %}

{% block content %}

    <h3>Add a family member</h3>
    <form class="family-table" action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
        <a href="{% url 'dashboard' %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/family_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Family Details</h1>
    <div>
        <div>
            <p>Fam_Name: {{ family.fam_name }}</p>
            <p>Description: {{ family.description }}</p>
        </div>
        <div>
            <a href="{% url 'families_update' family.id %}">Edit</a>
            <a href="{% url 'families_delete' family.id %}">Delete</a>
        </div>
    </div>

{% endblock %}

main_app/templates/family_index.html
{% extends 'base.html' %}

{% block title %}
List of Family Members
{% endblock %}

{% block content %}



<h3>{{header}}</h3>
    {% for family in families %}

    <a href="{% url 'families_show' family.id %}">
        <p>Fam_Name: {{family.fam_name}}</p>
    </a>
   
    {% endfor %}

{% endblock %} -->

main_app/templates/family_show.html
{% extends 'base.html' %}

{% block content %}
    <h1>Family Details</h1>

    <!-- I have to come back to this. I want user name shown with whom teh transaction is associated to -->
    <div>
        <div>
            <h4>Name: {{ family.fam_name }}</h4>
            <p>Description: {{ family.description }}</p>
            <p>Tasks:</p>
            {% for task in family.task_set.all %}
                <p>{{ task.name }}</p>
            {% empty %}
                <p>This is person doesn't have any tasks assigned to them.</p>
            {% endfor %}
        </div>

        <div>
            <a href="{% url 'families_update' family.id %}">Edit</a>
            <a href="{% url 'families_delete' family.id %}">Delete</a>
        </div>
    </div>

{% endblock %}

main_app/templates/family_update.html
<!-- {% extends 'base.html' %}

{% block content %}

<h5>Update {{family.fam_name}}</h5>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update"/>
    <a href="{% url 'family_detail' family.pk %}">Cancel</a>
</form>

{% endblock %} -->


{% extends 'base.html' %}

{% block content %}
    <h1>Update Family</h1>

    <form action="" method="post">
        {% csrf_token%}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Update">
        <a href="{% url 'family_detail' family.pk %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/landing_page.html
{% extends 'base.html' %}

{% block title %}
Family Banking System
{% endblock %}

{% block content %}
<div class="container">
    <h5>Welcome to FSB. This is an app where you can setup a family account and manage tasks and allowance for your child(ren) </h5>
    <p>Once, you have signed up, please log In to set your family account up and running!</p>
</div>
<div class="card">
    <h6>Create an account using the link below!</h6>
    <a class="" href="{% url 'signup' %}">SignUp</a>
</div>



{% endblock %}

main_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

{% if errors %}
<p style="color: red;">{{errors}}</p>
{% endif %}
<form action="" method="POST" class="register">
    <legend>
        <h3>Sign Up</h3>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="waves-effect waves-light btn grey darken-2" type="submit" value="Submit">
    </legend>
</form>
{% endblock %}



<!-- {% extends 'base.html' %}
{% load static %}


{% block content %}

    <h1>{{ username }}'s Tasks and Transactions</h1>

    {% for task in tasks %}
        <a href="/tasks/{{ task.id }}">
            <h3>{{ task.name }}</h3>
        </a>

    {% endfor %}

{% endblock %} -->






<!-- {% extends 'base.html' %}
{% load static %}


{% block content %}

    <h1>{{ username }}'s Tasks and Transactions</h1>

    {% for user in users %}
        <a href="/users/{{ user.id }}">
            <h3>{{ user.username }}</h3>
        </a>

    {% endfor %}

{% endblock %} -->

main_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}

{% if errors %}
<p style="color: red;">{{errors}}</p>
{% endif %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

main_app/templates/task_create.html
{% extends 'base.html' %}

{% block content %}

<h1>Add a Task!</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit" />
    <a href="{% url 'dashboard' %}">Cancel</a>
    
</form>

{% endblock %}

main_app/templates/task_detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <h5>Name: {{task.name}} </h5>
    <h5>Amount: {{task.amount}} </h5>
    <h5>Due Date: {{task.due_date}} </h5>
    <h5>Description: {{task.description}} </h5>
    <h5>Task-Status: {{task.task_status}} </h5>
    <h5>Task-Approval: {{task.task_approval}} </h5>
    
    <p>Created by:
        <a href="/user/{{ task.user.username }}">{{ task.user.username }}</a>
    </p>
    <h5>Task assigned to:</h5>
    
    <!-- {% for family in task.family.all %}
        <div>{{ family.fam_name }}</div>
    {% empty %}
        <div> This task has not been assigned to any family member yet 🙁</div>
    {% endfor %} -->
</div>
<div>
    <a href="{% url 'task_update' task.pk %}">Update</a>
    <a href="{% url 'task_delete' task.pk %}">Delete</a>
</div>

{% endblock %}

main_app/templates/tasklist.html
{% extends 'base.html' %}

{% block title %}
List of Tasks
{% endblock %}

{% block content %}


<h3>{{header}}</h3>
    {% for task in tasks %}

    <a href="{% url 'task_detail' task.pk %}">
        <h6>Name: {{task.name}}</h6>
    </a>
    
    <h6>Amount: {{task.amount}} </h6>
    <h6>Due Date: {{task.duedate}} </h6>
    <h6>Description: {{task.description}} </h6>
    <h6>Task Status: {{task.task_status}} </h6>
    <h6>Task Approval: {{task.task_approval}} </h6>
    <!-- <h6>Assigned To: {{task.username}} </h6> -->
    <p>Created by:
        <a href="/user/{{ task.user.username }}">{{ task.user.username }}</a>
    </p>
    
    {% endfor %}

{% endblock %}

main_app/templates/transaction_create.html
<!-- {% extends 'base.html' %}

{% block content %}

    <h3>Add a transaction</h3>
    <form class="transaction-table" action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!">
        <a href="{% url 'dashboard' %}">Cancel</a>
    </form>

{% endblock %} -->

main_app/templates/transaction_index.html
<!-- {% extends 'base.html' %}

{% block content %}
    <h3>List of Transactions</h3>

    {% for transaction in transactions %}
        <div>
            <div>
                <a href="{% url 'transactions_show' transaction.id %}">
                    <p>Amount: ${{ transaction.amount }}</p>
                </a>
            </div>
            <p>Date: {{transaction.date}} </p>
        </div>
        
    {% endfor %}

{% endblock %} -->

main_app/templates/transfer_funds.html
{% extends 'base.html' %}
{% block content %}

<h1>Transfer funds!</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit" />
</form>

{% endblock %}